export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const AUTHENTICATE_USER_ERROR = "AUTHENTICATE_USER_ERROR";

export const GET_POSTS = "GET_POSTS";
export const ADD_POST = "ADD_POST";


export const GET_LATEST_MOVIES = "GET_LATEST_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";

export const GET_SEARCH_MOVIES = "GET_SEARCH_MOVIES";


export const ADD_TO_WATCHLIST = "ADD_TO_WATCHLIST";
export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";

export const GET_TO_FAVORITE = "GET_TO_FAVORITE";
export const GET_TO_WATCHLIST = "GET_TO_WATCHLIST";

export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';

export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';

export const REMOVE_FROM_FAVORITE = 'REMOVE_FROM_FAVORITE'
